services:
  - docker
language: node_js
node_js:
  - node
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - yarn
script:
  - yarn build
  - yarn docker