services:
- docker
language: node_js
node_js:
- node
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- gcloud config set project 'default-docker-vm'
script:
# - yarn build
# - yarn docker:build
# - yarn docker:push
# - gcloud compute instances update-container docker \
#     --container-image dimkinv/eve-discord-bot-test
before_install:
- openssl aes-256-cbc -K $encrypted_25de5cd8b217_key -iv $encrypted_25de5cd8b217_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- gcloud version
- whitch gcloud
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash > /dev/null;
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib  
- gcloud auth activate-service-account --key-file client-secret.json