import { PriceResolver } from './price-resolver/get-price.resolver';
import { registerResolver as _registerResolver } from './register.resolver';
import { getPiResolver as _getPiResolver } from './get-pi.resolver';
import { aboutResolver as _aboutResolver } from './about-resolver/about.resolver';
import { priceRemindResolver as _priceRemindResolver } from './remind-resolvers/price-remind.resolver';
import { container } from '../configurations/inversify.config';
import { TYPES } from '../configurations/inversify.types';
import { IResolvable } from '../resolvers/i-resolvable';

const pResolver = container.get<IResolvable>(TYPES.PriceResolver);
const iResolver = container.get<IResolvable>(TYPES.InfoResolver);
const hResolver = container.get<IResolvable>(TYPES.HelpResolver);
const _rollResolver = container.get<IResolvable>(TYPES.RollResolver);
export const getPriceResolver = pResolver;
export const infoResolver = iResolver;
export const helpResolver = hResolver;
export const registerResolver = _registerResolver;
export const getPiResolver = _getPiResolver;
export const priceRemindResolver = _priceRemindResolver;
export const aboutResolver = _aboutResolver;
export const rollResolver = _rollResolver;