"use strict";
var get_price_resolver_1 = require("./get-price.resolver");
var help_resolver_1 = require("./help.resolver");
var register_resolver_1 = require("./register.resolver");
var get_pi_resolver_1 = require("./get-pi.resolver");
var about_resolver_1 = require("./about-resolver/about.resolver");
var price_remind_resolver_1 = require("./remind-resolvers/price-remind.resolver");
exports.getPriceResolver = get_price_resolver_1.getPriceResolver;
exports.helpResolver = help_resolver_1.helpResolver;
exports.registerResolver = register_resolver_1.registerResolver;
exports.getPiResolver = get_pi_resolver_1.getPiResolver;
exports.priceRemindResolver = price_remind_resolver_1.priceRemindResolver;
exports.aboutResolver = about_resolver_1.aboutResolver;
