"use strict";
var help_resolver_1 = require("./help.resolver");
var register_resolver_1 = require("./register.resolver");
var get_pi_resolver_1 = require("./get-pi.resolver");
var about_resolver_1 = require("./about-resolver/about.resolver");
var price_remind_resolver_1 = require("./remind-resolvers/price-remind.resolver");
var inversify_config_1 = require("../configurations/inversify.config");
var inversify_types_1 = require("../configurations/inversify.types");
var pResolver = inversify_config_1.container.get(inversify_types_1.TYPES.PriceResolver);
exports.getPriceResolver = pResolver;
exports.helpResolver = help_resolver_1.helpResolver;
exports.registerResolver = register_resolver_1.registerResolver;
exports.getPiResolver = get_pi_resolver_1.getPiResolver;
exports.priceRemindResolver = price_remind_resolver_1.priceRemindResolver;
exports.aboutResolver = about_resolver_1.aboutResolver;
